MODEL_PATH = "best.pt"

DIAL_RADIUS_RATIO = 0.15

OCR_LANGUAGES = ["en"]
OCR_GPU = False
OCR_MIN_CONF = 0.75
OCR_MAG_RATIO = 5
OCR_ALLOWLIST = "0123456789"

CROP_UPSCALE_FACTOR = 4

DIAL_MASK_RADIUS_MARGIN = 1.02
HAND_MASK_STRENGTHS = (1.0, 0.8, 0.6, 0.4, 0.2, 0.0)
HAND_MASK_MAX_THRESHOLD_SHIFT = 20.0
HAND_MASK_CLOSE_KERNEL_SIZE = (7, 7)
HAND_MASK_NUMBER_DILATE_KERNEL_SIZE = (9, 9)
HAND_MASK_OPEN_KERNEL_BASE_RATIO = 0.01
HAND_MASK_OPEN_KERNEL_STRENGTH_RATIO = 0.02
HAND_MASK_DILATE_ITERATIONS = 2
HAND_MASK_CENTER_RADIUS_RATIO = 0.07

HOUGH_RHO = 1
HOUGH_THETA_DIVISOR = 360
HOUGH_THRESHOLD = 30
HOUGH_MIN_LINE_LENGTH_RATIO = 0.12
HOUGH_MAX_LINE_GAP_RATIO = 0.06
HOUGH_MIN_LENGTH_CROP_RATIO = 0.15

DEDUP_SAME_DIRECTION_TOLERANCE_DEG = 10.0
DEDUP_SAME_ARM_TOLERANCE_DEG = 5.0
DEDUP_SAME_ARM_LENGTH_RATIO = 0.5
DEDUP_MAX_HANDS = 2

RAY_MAX_RADIUS_RATIO = 0.5
RAY_PATCH_RADIUS = 1
RAY_PERPENDICULAR_TOLERANCE = 3
RAY_GAP_TOLERANCE = 4

CLOCK_HOUR_CARRY_FRACTION_LOW = 0.25
CLOCK_HOUR_CARRY_FRACTION_HIGH = 0.75

# Colors are BGR tuples (OpenCV convention)
COLOR_MASK_OVERLAY = (0, 255, 255)
COLOR_NUMBER_BOX = (0, 255, 0)
COLOR_NUMBER_TEXT = (0, 255, 0)
COLOR_PAIR_LINE = (255, 0, 0)
COLOR_DIAL_CIRCLE = (255, 0, 170)
COLOR_MINUTE_HAND = (0, 200, 0)
COLOR_HOUR_HAND = (0, 0, 255)
COLOR_CENTER_DOT = (0, 0, 255)

MASK_OVERLAY_ALPHA = 0.2
MASK_BASE_ALPHA = 0.2

NUMBER_BOX_THICKNESS = 2
NUMBER_TEXT_SCALE = 0.55
NUMBER_TEXT_THICKNESS = 2
PAIR_LINE_THICKNESS = 1
DIAL_CIRCLE_THICKNESS = 2
HAND_LINE_THICKNESS = 2
HAND_LABEL_SCALE = 0.7
HAND_LABEL_THICKNESS = 2
CENTER_DOT_RADIUS = 6

HAND_LABELS = {0: "M", 1: "G"}

FLASK_DEBUG = True

